spring:
  kafka:
    bootstrap-servers: test:9092
    producer:
      retries: 0
      batch-size: 10000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
